// Front-end/Solid/src/components/EffectClock.tsx
import { createSignal, onCleanup } from 'solid-js';

function formatNow() {
  return new Date().toLocaleTimeString('zh-CN', { hour12: false });
}

export default function EffectClock() {
  const [label, setLabel] = createSignal(formatNow());

  const id = window.setInterval(() => setLabel(formatNow()), 1000);
  onCleanup(() => window.clearInterval(id));

  return (
    <section class="panel" id="effect">
      <h2>副作用与 onCleanup</h2>
      <p class="lead muted">
        在组件函数体内注册定时器；<code>onCleanup</code> 在卸载或热更新时清理，避免泄漏。
      </p>
      <p style={{ margin: 0, 'font-variant-numeric': 'tabular-nums' }}>{label()}</p>
    </section>
  );
}

// Front-end/Svelte/src/components/EffectClock.svelte
<script lang="ts">
  let ticks = $state(0);
  let running = $state(true);

  $effect(() => {
    if (!running) return;
    const id = window.setInterval(() => {
      ticks += 1;
    }, 1000);
    return () => window.clearInterval(id);
  });
</script>

<div class="panel">
  <h2>$effect 与清理</h2>
  <p class="lead muted">依赖 <code>running</code>；返回函数在依赖变化或卸载时执行，用于清理定时器。</p>
  <p style="margin: 0 0 10px; font-variant-numeric: tabular-nums">ticks: <strong>{ticks}</strong></p>
  <div class="row">
    <button type="button" class="secondary" onclick={() => (running = !running)}>
      {running ? '暂停' : '继续'}
    </button>
    <button type="button" class="secondary" onclick={() => (ticks = 0)}>归零</button>
  </div>
</div>
