// Front-end/Million/src/main.tsx
import { StrictMode, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './app.css';

function App() {
  const [count, setCount] = useState(0);
  const [draft, setDraft] = useState('');
  const [items, setItems] = useState<string[]>(['示例项']);

  const add = () => {
    const t = draft.trim();
    if (!t) return;
    setItems((prev) => [t, ...prev]);
    setDraft('');
  };

  return (
    <div className="shell">
      <h1>Million + React 能力展台</h1>
      <p className="lead muted">
        在常规 <strong>React 19</strong> 写法之上，由{' '}
        <code>million/compiler</code> 的 <strong>Vite 插件</strong>做自动优化（本页为最小对照示例）。
      </p>
      <ul className="tag-list">
        {['Million 3', 'React 19', 'Vite 8', 'TS'].map((t) => (
          <li key={t}>{t}</li>
        ))}
      </ul>
      <section className="panel">
        <h2>状态</h2>
        <p className="lead">计数：{count}</p>
        <div className="row">
          <button type="button" onClick={() => setCount((c) => c + 1)}>
            +1
          </button>
        </div>
      </section>
      <section className="panel">
        <h2>列表</h2>
        <div className="row">
          <input
            type="text"
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            placeholder="新条目"
          />
          <button type="button" className="secondary" onClick={add}>
            添加
          </button>
        </div>
        <ul>
          {items.map((x, i) => (
            <li key={`${i}-${x}`}>{x}</li>
          ))}
        </ul>
      </section>
    </div>
  );
}

createRoot(document.getElementById('app')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
);

// Front-end/WebComponents/src/main.ts
import './app.css';

class ShowcaseApp extends HTMLElement {
  private count = 0;
  private draft = '';
  private items: string[] = ['示例项'];

  connectedCallback() {
    this.addEventListener('click', this);
    this.addEventListener('input', this);
    this.paint();
  }

  disconnectedCallback() {
    this.removeEventListener('click', this);
    this.removeEventListener('input', this);
  }

  private paint() {
    const itemsHtml = this.items
      .map((x) => `<li>${ShowcaseApp.escape(x)}</li>`)
      .join('');
    this.innerHTML = `
      <div class="shell">
        <h1>Web Components（原生）能力展台</h1>
        <p class="lead muted">
          仅用 <strong>Custom Elements</strong> 与 <strong>HTMLElement</strong>，无 Lit 等封装；状态保存在组件实例字段中。
        </p>
        <ul class="tag-list">
          <li>Custom Elements</li>
          <li>Vite 8</li>
          <li>TS</li>
        </ul>
        <section class="panel">
          <h2>状态</h2>
          <p class="lead">计数：<span data-ref="count">${this.count}</span></p>
          <div class="row">
            <button type="button" data-action="inc">+1</button>
          </div>
        </section>
        <section class="panel">
          <h2>列表</h2>
          <div class="row">
            <input type="text" data-ref="draft" placeholder="新条目" value="${ShowcaseApp.escape(this.draft)}" />
            <button type="button" class="secondary" data-action="add">添加</button>
          </div>
          <ul data-ref="list">${itemsHtml}</ul>
        </section>
      </div>
    `;
  }

  private static escape(s: string): string {
    return s
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/"/g, '&quot;');
  }

  /** `EventListener`：委托处理点击与输入，避免在 `innerHTML` 上使用内联处理器。 */
  handleEvent(ev: Event) {
    if (ev.type === 'input' && ev.target instanceof HTMLInputElement) {
      if (ev.target.matches('[data-ref="draft"]')) {
        this.draft = ev.target.value;
      }
      return;
    }
    if (ev.type === 'click' && ev.target instanceof HTMLElement) {
      const action = ev.target.closest('[data-action]')?.getAttribute('data-action');
      if (action === 'inc') {
        this.count += 1;
        this.paint();
      }
      if (action === 'add') {
        const t = this.draft.trim();
        if (!t) return;
        this.items = [t, ...this.items];
        this.draft = '';
        this.paint();
      }
    }
  }
}

customElements.define('showcase-app', ShowcaseApp);
