// Front-end/Angular/src/app/components/show-demo.component.ts
import { Component, signal } from '@angular/core';

@Component({
  selector: 'app-show-demo',
  standalone: true,
  template: `
    <section class="panel" id="show">
      <h2>&#64;if / &#64;else</h2>
      <p class="lead muted">内置控制流替代旧版 <code>*ngIf</code>，分支类型更直观。</p>
      <div class="row" style="margin-bottom: 8px">
        <button type="button" class="secondary" (click)="visible.set(!visible())">切换显示</button>
      </div>
      @if (visible()) {
        <p style="margin: 0">主内容可见。</p>
      } @else {
        <p class="muted">当前为隐藏态（&#64;else）</p>
      }
    </section>
  `,
})
export class ShowDemoComponent {
  readonly visible = signal(true);
}

// Front-end/Solid/src/components/ShowDemo.tsx
import { Show, createSignal } from 'solid-js';

export default function ShowDemo() {
  const [visible, setVisible] = createSignal(true);

  return (
    <section class="panel" id="show">
      <h2>Show</h2>
      <p class="lead muted">
        条件渲染 + <code>fallback</code>，类型在分支间收窄。
      </p>
      <div class="row" style={{ 'margin-bottom': '8px' }}>
        <button type="button" class="secondary" onClick={() => setVisible((v) => !v)}>
          切换显示
        </button>
      </div>
      <Show when={visible()} fallback={<p class="muted">当前为隐藏态（fallback）</p>}>
        <p style={{ margin: 0 }}>主内容可见。</p>
      </Show>
    </section>
  );
}
