// Front-end/Angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { EffectClockComponent } from './components/effect-clock.component';
import { ForTodoComponent } from './components/for-todo.component';
import { ShowDemoComponent } from './components/show-demo.component';
import { SignalsDemoComponent } from './components/signals-demo.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    SignalsDemoComponent,
    EffectClockComponent,
    ForTodoComponent,
    ShowDemoComponent,
  ],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent {
  readonly nav: readonly { href: string; label: string }[] = [
    { href: '#signals', label: 'Signals' },
    { href: '#effect', label: 'RxJS' },
    { href: '#for', label: '@for' },
    { href: '#show', label: '@if' },
  ];

  readonly tags: readonly string[] = [
    'Angular 独立运行时',
    'signal / computed',
    '@for / @if 控制流',
    'Standalone 组件',
    'CLI + esbuild 应用构建',
    'Zone.js 变更检测',
  ];
}

<div class="shell">
  <header class="hero">
    <img src="/angular.svg" width="44" height="44" alt="Angular logo" />
    <div class="hero-text">
      <h1>Angular 能力展台</h1>
      <p class="lead muted">
        与 React / Vue / Svelte / Solid 子项目相同：<strong>独立前端工程</strong>、无后端依赖。本示例使用
        <strong>Angular CLI</strong>（非 Vite），突出 <strong>signal</strong>、内置控制流与 Standalone 组件。
      </p>
    </div>
  </header>

  <nav class="demo-nav" aria-label="章节">
    <ul>
      @for (item of nav; track item.href) {
        <li>
          <a [href]="item.href" class="nav-a">{{ item.label }}</a>
        </li>
      }
    </ul>
  </nav>

  <section id="features" class="feature-block" aria-label="能力标签">
    <p class="muted" style="margin: 0 0 6px">
      下列标签对应本页组件；可对照其它子项目的响应式与列表写法。
    </p>
    <ul class="tag-list">
      @for (t of tags; track t) {
        <li>{{ t }}</li>
      }
    </ul>
  </section>

  <main class="grid">
    <app-signals-demo />
    <app-effect-clock />
    <app-for-todo />
    <app-show-demo />
  </main>

  <footer class="foot muted">
    编辑 <code>src/app/app.component.html</code> 与 <code>src/app/components/*</code> 体验热替换；说明见
    <code>ANGULAR-CLI-TypeScript.md</code>。
  </footer>
</div>

// Front-end/Solid/src/App.tsx
import { For, type Component } from 'solid-js';
import solidLogo from './assets/solid.svg';
import EffectClock from './components/EffectClock';
import ForTodoDemo from './components/ForTodoDemo';
import ShowDemo from './components/ShowDemo';
import SignalsDemo from './components/SignalsDemo';

const nav = [
  { href: '#signals', label: 'Signals' },
  { href: '#effect', label: 'onCleanup' },
  { href: '#for', label: 'For' },
  { href: '#show', label: 'Show' },
] as const;

const tags = [
  'Solid 细粒度响应式',
  'createSignal / createMemo',
  '<For each> 键控列表',
  '<Show when / fallback>',
  'JSX + 编译器优化',
  'render() 入口',
];

const App: Component = () => {
  return (
    <div class="shell">
      <header class="hero">
        <img src={solidLogo} width="44" height="44" alt="Solid logo" />
        <div class="hero-text">
          <h1>Solid 能力展台</h1>
          <p class="lead muted">
            与 React / Vue / Svelte 子项目相同：<strong>Vite + TypeScript</strong>、纯前端无后端。本页突出 Solid 的
            <strong>信号驱动 JSX</strong>（无虚拟 DOM  diff、按依赖更新 DOM）。
          </p>
        </div>
      </header>

      <nav class="demo-nav" aria-label="章节">
        <ul>
          <For each={Array.from(nav)}>
            {(item) => (
              <li>
                <a href={item.href} class="nav-a">
                  {item.label}
                </a>
              </li>
            )}
          </For>
        </ul>
      </nav>

      <section id="features" class="feature-block" aria-label="能力标签">
        <p class="muted" style={{ margin: '0 0 6px' }}>
          下列标签对应本页组件；可对照 React Hooks、Vue <code>ref</code> / <code>computed</code>、Svelte runes 阅读差异。
        </p>
        <ul class="tag-list">
          <For each={tags}>{(t) => <li>{t}</li>}</For>
        </ul>
      </section>

      <main class="grid">
        <SignalsDemo />
        <EffectClock />
        <ForTodoDemo />
        <ShowDemo />
      </main>

      <footer class="foot muted">
        编辑 <code>src/App.tsx</code> 与 <code>src/components/*</code> 体验 HMR；说明见
        <code>SOLID-Vite-TypeScript.md</code>。
      </footer>
    </div>
  );
};

export default App;
